version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgresserver
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password